name: Update Infrastructure

on: workflow_dispatch

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ vars.AWS_REGION }}
  TF_VAR_rds_password: ${{ secrets.TF_VAR_rds_password }}
  TF_VAR_laravel_app_key: ${{ vars.TF_VAR_laravel_app_key }}
  TF_VAR_alb_certificate_arn: ${{ vars.TF_VAR_alb_certificate_arn }}

jobs:
  destroy-infrastructure:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Update Infrastructure
        working-directory: ./infrastructure
        run: terraform init && terraform apply -auto-approve
